### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by FernandoMiguel** [jSherz/4dots#2]
you probably want to add the .terraform state to gitignore

**Comment by jSherz** [comment]
Hi Fernando. Thank you for pointing this out. I created this repository for a technical assessment and so the infrastructure it describes is no longer in use (and was deleted). Normally I would not store the tfstate in the repository but I left it here as an example.

Thanks for bringing this up though as it would otherwise have been a mistake! 👍 

James
